backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
 
 
# This line should *not* be indented
publish_mode: editorial_workflow


# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads

#Preview Links
show_preview_links: false

#Brand Logo
logo_url: https://jeff-vet-test.netlify.app/assets/hcvnyc-icon.svg


collections:
  - label: "News"
    name: "news"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/layout_post.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["posts", "news"]}
      - {label: "Category", name: "category", widget: "hidden", default: "News"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homeData"
        file: "_data/homeData.json"
        fields:
          - {label: "Home Hero Paragraphs", name: "hero", widget: "list", summary: "Paragraph", field: {label: Paragraph, name: paragraph, widget: markdown}, allow_add: true}
      - label: "About Page"
        name: "aboutData"
        file: "_data/aboutData.json"
        fields:
          - {label: "About Image", name: "img", widget: "image"}
          - {label: "About Paragraphs", name: "des", widget: "list", summary: "Paragraph", field: {label: Paragraph, name: paragraph, widget: markdown}, allow_add: true}
      - label: "Testimonials Page"
        name: "testimonialsData"
        file: "_data/testimonialsData.json"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            summary: "Testimonial"
            fields:
              - {label: "Testimonial Image", name: "img", widget: "image"}
              - {label: Name, name: name, widget: string}
              - {label: Quote, name: quote, widget: string}
              - {label: Author, name: author, widget: string}
            allow_add: true
      - label: "Services Page"
        name: "servicesData"
        file: "_data/servicesData.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            summary: "Service"
            fields:
              - {label: "Format", name: "format", widget: "hidden"}
              - {label: Image, name: img, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: "Paragraphs", name: "des", widget: "list", summary: "Paragraph", field: {label: Paragraph, name: paragraph, widget: markdown}, allow_add: true}
            allow_add: false